### PR TITLE
Re-implement patch for horizontal scrolling and extra mouse buttons

### LINKED ISSUE #51: Additional mouse button support
### Operating Systems ###

Server: Fedora 28

Client: Windows 10 Build 1803

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

1. Use a mouse that has additional buttons (i.e forward and back buttons)
2. Try and use those buttons while in the client

### Other info ###

It would be nice if at least the forward and back buttons would work.

### PR DESCRIPTION
**Pull request by EbonJaeger**
Re-implementation of #242 for the newer CI's and an up to date codebase. Both horizontal scrolling and extra mouse buttons (buttons 4 and 5, sometimes also referred to as forward and back) have been tested between Windows 10 and Linux (Solus OS). I don't have any macOS devices, so if someone wants to build this to test that platform, that might be a good idea.

Aside from some formatting and a couple of additional comments, there are no significant changes from the original work done in the previous PR.

Fixes #51

### CODE REVIEW

File: src/lib/platform/MSWindowsDesks.cpp [hunk 1]
```diff
@@ -602,6 +606,16 @@ MSWindowsDesks::deskThread(void* vdesk)
 {
     MSG msg;
 
+	BOOL vistaOrGreater = FALSE;
+
+	{
```
Comment (p12tic) [inline src/lib/platform/MSWindowsDesks.cpp]: strange indentation

File: src/lib/platform/XWindowsScreen.cpp [hunk 2]
```diff
@@ -829,35 +830,37 @@ XWindowsScreen::fakeMouseRelativeMove(SInt32 dx, SInt32 dy) const
...
+    int numEvents;
 
-    int numEvents = accumulateMouseScroll(yDelta);
+    if ((!xDelta && !yDelta) || (xDelta && yDelta)) {
+        // Invalid scrolling inputs
+        return;
+    }
 
-    // choose button depending on rotation direction
-    const unsigned int xButton = mapButtonToX(static_cast<ButtonID>(
```
Comment (p12tic) [inline src/lib/platform/XWindowsScreen.cpp]: Why this workaround got deleted?

File: src/lib/platform/MSWindowsDesks.cpp [hunk 3]
```diff
@@ -602,6 +606,16 @@ MSWindowsDesks::deskThread(void* vdesk)
 {
     MSG msg;
 
+	BOOL vistaOrGreater = FALSE;
```
Comment (p12tic) [inline src/lib/platform/MSWindowsDesks.cpp]: I think it would be best to extract this chunk of code to a separate function, for example `isVistaOrGreater`

File: src/lib/platform/MSWindowsDesks.cpp (hunk 1 above)
Comment (EbonJaeger) [reply src/lib/platform/MSWindowsDesks.cpp]: Yeah, the indentation is a mess; the same file uses both spaces and tabs and its hard to tell which is which. I'll try to make it more consistent.

File: src/lib/platform/MSWindowsDesks.cpp (hunk 3 above)
Comment (EbonJaeger) [reply src/lib/platform/MSWindowsDesks.cpp]: Agreed. There exist version helper functions for Windows, would it be better to use those instead? https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindowsvistaorgreater

File: src/lib/platform/XWindowsScreen.cpp (hunk 2 above)
Comment (EbonJaeger) [reply src/lib/platform/XWindowsScreen.cpp]: I don't believe this workaround was actually doing anything; the values passed to `mapButtonToX` was always either `-1` or `-2`, which got mapped to `4` and `5` respectively. I don't see how it could ever return `0` here, and thus go into the `if` block.

Comment (p12tic) [reply src/lib/platform/XWindowsScreen.cpp]: Sounds reasonable then.

Comment (p12tic) [reply src/lib/platform/XWindowsScreen.cpp]: I would have done this removal as a separate commit though, it would be much clearer to anyone who comes by it in the git history.

File: src/lib/platform/MSWindowsDesks.cpp (hunk 3 above)
Comment (p12tic) [reply src/lib/platform/MSWindowsDesks.cpp]: Indeed, a standard helper in this case makes sense.

File: src/lib/platform/MSWindowsDesks.cpp (hunk 1 above)
Comment (p12tic) [reply src/lib/platform/MSWindowsDesks.cpp]: I think it makes sense to gradually move to spaces. Various tools display tabs differently, using spaces works around this issue very well.

Comment (EbonJaeger) [reply src/lib/platform/MSWindowsDesks.cpp]: True. Luckily it doesn't matter anymore in this case, since this was just replaced by a Windows function. :D

File: src/lib/platform/MSWindowsDesks.cpp (hunk 3 above)
Comment (EbonJaeger) [reply src/lib/platform/MSWindowsDesks.cpp]: Done!

**Comment by EbonJaeger** [comment]
Any other input on this so far?

**Comment by p12tic** [comment]
@AdrianKoshka : This PR is good to go.
