### PR TITLE
Use ansi codepage for internal multibyte strings on windows (fixes #976, fixes #974, fixes #444)

### LINKED ISSUE #444: Barrier.exe : no configuration avilable
Os : windows 10
Issues ;
Shortcut is not created on dekstop.
When barriers is launched from folder , 
No configuration available is displayed

### LINKED ISSUE #974: Not able to open trustedServers.txt if username contains wide characters e.g. Chinese characters
**Describe the bug**
SSL-enabled session failed to start. Barrier is unable to open the right created trustedServers.txt. I am wondering that's because the path contains wide characters, since my username is in wide characters.

**To Reproduce**

1. Run barrier by a user with name contains wide character
2. Set as client and enable SSL
3. Connect a SSL-enabled server
4. After trusted the peer, the service does not actually running. Error log is found.

**Expected behavior**
Works with username contains wide character

**Screenshots**

Please do not link to image hosting sites, as these can be ephemeral. Instead, attach them to the issue. 

Error log:
```
[2020-12-07T11:57:10] INFO: service command updated
[2020-12-07T11:57:11] NOTE: connecting to '10.10.xxx.xxx': 10.10.xxx.xx:24800
[2020-12-07T11:57:11] INFO: OpenSSL 1.0.2l  25 May 2017
[2020-12-07T11:57:11] NOTE: server fingerprint: DD:90:85:3F:50:B9:84:04:80:8E:46:92:A6:71:9D:5F:83:3D:18:32
[2020-12-07T11:57:11] NOTE: trustedServersFilename: C:\Users\小明\AppData\Local\Barrier/SSL/Fingerprints/TrustedServers.txt
[2020-12-07T11:57:11] NOTE: Unable to open trustedServersFile: C:\Users\小明\AppData\Local\Barrier/SSL/Fingerprints/TrustedServers.txt
[2020-12-07T11:57:11] ERROR: failed 
```

**Desktop (please complete the following information):**

 - OS: Windows 10
- Barrier version 2.3.3

**Additional context**

Server is barrier 2.3.3 running on Fedora 32. Connection can be established if SSL-disabled on both sides.

### LINKED ISSUE #976: Windows10 client: unable to open trustetedServersFile - Username with space
on a Windows Client i have a space and "ä" in the username. 
The File trustedServers.txt is written correctly, fingerprint is ok. 
The log on client shows continuously: Unable to open trustetedServersFile: C:\Users\xxx xäx\AppData\Local\Barrier...

someone has similar problems with linux client and chinese symbols i think. New issue do to win client.

Thanks for your help in advance

### PR DESCRIPTION
**Pull request by albertony**
Fixes https://github.com/debauchee/barrier/issues/976
Fixes https://github.com/debauchee/barrier/issues/974
Fixes https://github.com/debauchee/barrier/issues/444

Probably conflicts with https://github.com/debauchee/barrier/pull/972, but if you accept both PRs then just "ping" me and I can quickly fix it (either if I can merge the PR branches together, or you can merge one of them to master first and I rebase the other one, or something else..?)

### CODE REVIEW

**Review by p12tic — APPROVED** [review]

File: src/lib/common/win32/KnownFolderPaths.h [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+*/
+
+#pragma once
+
+#include <string>
+
+class KnownFolderPaths
+{
+public:
+    static std::string desktop();
```
Comment (p12tic) [inline src/lib/common/win32/KnownFolderPaths.h:25]: I think it makes sense to have these as simple functions.

**Review by p12tic — CHANGES_REQUESTED** [review]
Thanks for working on this! I had just one comment, looks good otherwise.

File: src/lib/common/win32/KnownFolderPaths.h (hunk 1 above)
Comment (albertony) [reply src/lib/common/win32/KnownFolderPaths.h]: Pushed an update, but not sure if it was something like this you had in mind, or something else? (and if so, I'm happy to make another attempt)

Comment (albertony) [reply src/lib/common/win32/KnownFolderPaths.h]: Pushed another update, because I managed to track down another one of those codepage issues. Refactored the KnowFolderPaths into a header-only, and added another one, StringConverters.h, for windows string conversions (narrow ansi, narrow utf8, and wide). But again, just let me know if you think it would be better doing it differently!

File: src/lib/common/win32/KnownFolderPaths.h [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+* You should have received a copy of the GNU General Public License
+* along with this program.  If not, see <http://www.gnu.org/licenses/>.
+*/
+
+#pragma once
+#include "StringConverters.h"
+#include <string>
+#include <Shlobj.h>
+
+static std::string known_folder_path(const KNOWNFOLDERID& id)
```
Comment (p12tic) [inline src/lib/common/win32/KnownFolderPaths.h:23]: `static` is incorrect for functions that are in the headers and are supposed to be reused in many cpp files. In such case there's a separate copy of the function in each translation unit and we rely on the linker to deduplicate.

Better to use `inline`.

Even better would be to add a .cpp file for the implementations.

The same applies to a header below.

**Comment by albertony** [comment]
Better than ever? :)

**Comment by albertony** [comment]
Tracked down a couple of more issues.. There were multiple similar problems, in client, server and deamon, so it took several attempts to track them down and fix them. Not entirely sure all are properly handled yet, I hope so, and think so, but let's wait a little bit and see if @cheese, reporter of https://github.com/debauchee/barrier/issues/974, will agree...

In general I guess the main solution is to be explicit about use of UTF-8 for strings sent over IPC, and to be sure to use current locale encoding (normally "ANSI" on Windows) for std::string's. E.g. QString::toStdString uses UTF-8, which is somewhat annoying (although [UTF-8 Everywhere](utf8everywhere.org/) is a thing, its not a short term solution here).

**Comment by albertony** [comment]
Done.
- Consistent use of std::string with standard locale-specific encoding.
- IPC messages always encode strings with UTF-8, which are converted back and forth at each end.
- In GUI layer, using Qt's `QString::fromLocal8Bit`/`QString::toLocal8Bit` to convert between (unicode) QString and (locale-specific) std::string, and `QString::fromUtf8`/`QString:toUtf8` for reading/writing UTF-8 encoded strings for IPC communication. So encoding is quite explicit. Not using `toStdString`/`fromStdString`, since it returns std::string that are UTF-8 encoded and leads to confusion and problems.
- In kernel: Locale encoded std::string, using the existing `Unicode::UTF8ToText`/`Unicode::textToUTF8` for UTF-8 specific IPC strings (except in this one place, in DataDirectories, since it is in common lib and do not have access to Unicode class in base lib).

**Review by p12tic — APPROVED** [review]

**Comment by p12tic** [comment]
Thanks!
